// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

/*
Package api_pb is a generated protocol buffer package.

It is generated from these files:
	book.proto

It has these top-level messages:
	Book
	ListBooksRequest
	ListBooksResponse
	GetBookRequest
	CreateBookRequest
	UpdateBookRequest
	DeleteBookRequest
*/
package api_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Book struct {
	BookId string `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Author string `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Book) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type ListBooksRequest struct {
}

func (m *ListBooksRequest) Reset()                    { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()               {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListBooksResponse struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *ListBooksResponse) Reset()                    { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()               {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type GetBookRequest struct {
	BookId string `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
}

func (m *GetBookRequest) Reset()                    { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()               {}
func (*GetBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type CreateBookRequest struct {
	Book *Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
}

func (m *CreateBookRequest) Reset()                    { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()               {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookRequest struct {
	Book *Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
}

func (m *UpdateBookRequest) Reset()                    { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()               {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type DeleteBookRequest struct {
	BookId string `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
}

func (m *DeleteBookRequest) Reset()                    { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()               {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "com.github.gky360.grpc_awesome_app.api.Book")
	proto.RegisterType((*ListBooksRequest)(nil), "com.github.gky360.grpc_awesome_app.api.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "com.github.gky360.grpc_awesome_app.api.ListBooksResponse")
	proto.RegisterType((*GetBookRequest)(nil), "com.github.gky360.grpc_awesome_app.api.GetBookRequest")
	proto.RegisterType((*CreateBookRequest)(nil), "com.github.gky360.grpc_awesome_app.api.CreateBookRequest")
	proto.RegisterType((*UpdateBookRequest)(nil), "com.github.gky360.grpc_awesome_app.api.UpdateBookRequest")
	proto.RegisterType((*DeleteBookRequest)(nil), "com.github.gky360.grpc_awesome_app.api.DeleteBookRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BookService service

type BookServiceClient interface {
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*Book, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := grpc.Invoke(ctx, "/com.github.gky360.grpc_awesome_app.api.BookService/ListBooks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := grpc.Invoke(ctx, "/com.github.gky360.grpc_awesome_app.api.BookService/GetBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := grpc.Invoke(ctx, "/com.github.gky360.grpc_awesome_app.api.BookService/CreateBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := grpc.Invoke(ctx, "/com.github.gky360.grpc_awesome_app.api.BookService/UpdateBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/com.github.gky360.grpc_awesome_app.api.BookService/DeleteBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceServer interface {
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	CreateBook(context.Context, *CreateBookRequest) (*Book, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*Book, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*google_protobuf1.Empty, error)
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.gky360.grpc_awesome_app.api.BookService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.gky360.grpc_awesome_app.api.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.gky360.grpc_awesome_app.api.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.gky360.grpc_awesome_app.api.BookService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.gky360.grpc_awesome_app.api.BookService/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.gky360.grpc_awesome_app.api.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _BookService_ListBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookService_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookService_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}

func init() { proto.RegisterFile("book.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6b, 0x14, 0x41,
	0x10, 0x65, 0x92, 0xec, 0x24, 0xa9, 0xc0, 0x92, 0x2d, 0x62, 0x1c, 0x46, 0x85, 0xd0, 0x82, 0x44,
	0x08, 0x3d, 0xb2, 0x81, 0xa0, 0x9e, 0x64, 0x55, 0x44, 0xd0, 0xcb, 0x4a, 0x10, 0xbc, 0x2c, 0x3d,
	0xbb, 0xed, 0xa4, 0xd9, 0x8f, 0x6e, 0xa7, 0x7b, 0x94, 0x45, 0xbc, 0x78, 0x13, 0x2f, 0x82, 0x37,
	0x7f, 0x96, 0xfe, 0x05, 0x7f, 0x88, 0x74, 0xf7, 0xac, 0xbb, 0x71, 0x58, 0x98, 0x91, 0x1c, 0xab,
	0xbb, 0xea, 0xd5, 0xab, 0x7a, 0x8f, 0x02, 0x48, 0xa5, 0x1c, 0x53, 0x95, 0x4b, 0x23, 0xf1, 0xce,
	0x50, 0x4e, 0x69, 0x26, 0xcc, 0x45, 0x91, 0xd2, 0x6c, 0x3c, 0x3f, 0x3d, 0xbb, 0x47, 0xb3, 0x5c,
	0x0d, 0x07, 0xec, 0x03, 0xd7, 0x72, 0xca, 0x07, 0x4c, 0x29, 0xca, 0x94, 0x88, 0x6f, 0x66, 0x52,
	0x66, 0x13, 0x9e, 0x30, 0x25, 0x12, 0x36, 0x9b, 0x49, 0xc3, 0x8c, 0x90, 0x33, 0xed, 0x51, 0xe2,
	0x1b, 0xe5, 0xaf, 0x8b, 0xd2, 0xe2, 0x6d, 0xc2, 0xa7, 0xca, 0xcc, 0xfd, 0x27, 0x79, 0x09, 0x5b,
	0x3d, 0x29, 0xc7, 0x78, 0x1d, 0xb6, 0x6d, 0xe3, 0x81, 0x18, 0x45, 0xc1, 0x51, 0x70, 0xbc, 0xdb,
	0x0f, 0x6d, 0xf8, 0x7c, 0x84, 0x07, 0xd0, 0x32, 0xc2, 0x4c, 0x78, 0xb4, 0xe1, 0x9e, 0x7d, 0x80,
	0x87, 0x10, 0xb2, 0xc2, 0x5c, 0xc8, 0x3c, 0xda, 0xf4, 0xd9, 0x3e, 0x22, 0x08, 0xfb, 0x2f, 0x84,
	0x36, 0x16, 0x52, 0xf7, 0xf9, 0xbb, 0x82, 0x6b, 0x43, 0x5e, 0x43, 0x67, 0xe5, 0x4d, 0x2b, 0x39,
	0xd3, 0x1c, 0x7b, 0xd0, 0xb2, 0x0d, 0x74, 0x14, 0x1c, 0x6d, 0x1e, 0xef, 0x75, 0x4f, 0x68, 0xbd,
	0x51, 0xa9, 0x45, 0xe9, 0xfb, 0x52, 0x72, 0x17, 0xda, 0xcf, 0xb8, 0xc3, 0x2d, 0x5b, 0xad, 0x9d,
	0x82, 0x9c, 0x43, 0xe7, 0x71, 0xce, 0x99, 0xe1, 0xab, 0xd9, 0x8f, 0x60, 0xcb, 0x7e, 0xbb, 0xd4,
	0xa6, 0x14, 0x5c, 0xa5, 0x85, 0x3d, 0x57, 0xa3, 0x2b, 0x87, 0x3d, 0x81, 0xce, 0x13, 0x3e, 0xe1,
	0x97, 0x61, 0xd7, 0xcd, 0xd6, 0xfd, 0xd9, 0x82, 0x3d, 0x9b, 0xf8, 0x8a, 0xe7, 0xef, 0xc5, 0x90,
	0xe3, 0xb7, 0x00, 0x76, 0xff, 0x2e, 0x1c, 0xef, 0xd7, 0xed, 0xff, 0xaf, 0x6e, 0xf1, 0x83, 0xff,
	0xa8, 0xf4, 0xea, 0x92, 0xf6, 0xe7, 0x5f, 0xbf, 0xbf, 0x6f, 0xec, 0x60, 0x98, 0x38, 0xa5, 0xf0,
	0x4b, 0x00, 0xdb, 0xa5, 0x54, 0x78, 0x56, 0x17, 0xf6, 0xb2, 0xb6, 0x71, 0xa3, 0x45, 0x92, 0xc8,
	0x31, 0x40, 0xdc, 0xf7, 0x0c, 0x92, 0x8f, 0xe5, 0xee, 0x3e, 0xe1, 0xd7, 0x00, 0x60, 0xe9, 0x05,
	0xac, 0x3d, 0x65, 0xc5, 0x3f, 0x0d, 0x19, 0x1d, 0x38, 0x46, 0x6d, 0x52, 0xee, 0xe4, 0xa1, 0x93,
	0x1a, 0x7f, 0x04, 0x00, 0x4b, 0x0b, 0xd5, 0x67, 0x53, 0xb1, 0x5d, 0x43, 0x36, 0xb7, 0x1d, 0x9b,
	0x5b, 0xdd, 0x6b, 0xab, 0xfb, 0xa1, 0x8b, 0x25, 0x95, 0xe4, 0xe6, 0x00, 0x4b, 0x1f, 0xd6, 0xe7,
	0x56, 0xf1, 0x6e, 0x7c, 0x48, 0xfd, 0x0d, 0xa2, 0x8b, 0x1b, 0x44, 0x9f, 0xda, 0x1b, 0xb4, 0x50,
	0xa9, 0x5b, 0x51, 0xa9, 0xb7, 0xf3, 0x26, 0x64, 0x4a, 0x0c, 0x54, 0x9a, 0x86, 0xae, 0xe6, 0xf4,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0x0d, 0x2d, 0xf5, 0x19, 0x05, 0x00, 0x00,
}
